name: observe_internet_connectivity
description: A flutter package that helps to observe internet connection via a customizable observing strategy.
version: 1.0.2
homepage: https://github.com/De-Morgan/observe_internet_connectivity

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
